name: demo workflow #name of the workflow

on: workflow_dispatch #[workflow_dispatch, push, pull_request] # Specifies the events that trigger the workflow

jobs:
  first-job: #name of the job
    runs-on: Ubuntu-latest # more options can be seen from https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    steps:
      - name: <name of the step>
        run: echo "Hello world!" #or uses: action/checkout@v2 # any of the 2 can be used either a command using run: keyword or an action using uses: keyword
      
      - name:  <name of the step> #another step if needed, a job can have multiple steps
        run:  | #the commands can be written in multiple lines using "|"
            echo "Hello World! " 
            echo "Using a multi-line command"
  second-job: #name of the other job, a workflow can have multiple jobs
    runs-on: windows-latest
    steps:
      - name: <name of the step>
        run: echo "i am second step"
